# Generated by Django 4.1.2 on 2022-11-26 20:37

from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations

def create_superuser(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.create_superuser(
        username="admin",
        password=settings.SUPERUSER_PASSWORD,
        first_name="Guardian",
        last_name="of the Galaxy",
        email="battlecode@mit.edu",
    )

def create_dev_group(apps, schema_editor):
    # Permissions are not created yet, so we force them to exist.
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)

    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    dev_administrator, _ = Group.objects.get_or_create(name="dev_administrators")
    dev_administrator.permissions.set(Permission.objects.all())

class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(create_dev_group),
    ]
