# Generated by Django 4.1.2 on 2022-11-28 17:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_add_superuser_and_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
