# Generated by Django 4.1.2 on 2022-12-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_add_superuser_and_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar_uuid",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
