# Generated by Django 4.1.2 on 2022-12-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userprofile_avatar_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="has_avatar",
            new_name="has_uploaded_avatar",
        ),
    ]
