# Generated by Django 4.1.2 on 2023-01-16 00:53

from django.db import migrations
import siarnaq.api.user.managers


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userprofile_country"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", siarnaq.api.user.managers.UserManager()),
            ],
        ),
    ]
