/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Episode {
    name_short: string;

    name_long: string;

    blurb?: string;

    game_release: string;

    language: models.LanguageEnum;

    scaffold?: string;

    artifact_name?: string;

    release_version_public?: string;

    release_version_saturn?: string;

    eligibility_criteria: Array<models.EligibilityCriterion>;

    frozen: boolean;

}
export namespace Episode {
}
