/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Episode {
    nameShort: string;

    nameLong: string;

    blurb?: string;

    gameRelease: string;

    language: models.LanguageEnum;

    scaffold?: string;

    artifactName?: string;

    releaseVersionPublic?: string;

    releaseVersionSaturn?: string;

    eligibilityCriteria: Array<models.EligibilityCriterion>;

    frozen: boolean;

}
export namespace Episode {
}
