/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Match {
    id: number;

    status: models.StatusBccEnum;

    episode: string;

    tournament_round: number;

    participants: Array<models.MatchParticipant>;

    maps: Array<string>;

    alternate_order: boolean;

    created: string;

    is_ranked: boolean;

    replay_url: string;

}
export namespace Match {
}
