/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ScrimmageRequest {
    id: number;

    episode: string;

    created: string;

    status: models.ScrimmageRequestStatusEnum;

    isRanked: boolean;

    requestedBy: number;

    requestedByName: string;

    requestedByRating: number;

    requestedTo: number;

    requestedToName: string;

    requestedToRating: number;

    playerOrder: models.PlayerOrderEnum;

    maps: Array<string>;

    mapNames: Array<string>;

}
export namespace ScrimmageRequest {
}
