/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TeamPublic {
    id: number;

    profile?: models.TeamProfilePublic;

    episode: string;

    name: string;

    members: Array<models.UserPublic>;

    status: models.Status526Enum;

    hasActiveSubmission: string;

}
export namespace TeamPublic {
}
