/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Tournament {
    nameShort: string;

    nameLong: string;

    blurb?: string;

    episode: string;

    style: models.StyleEnum;

    displayDate: string;

    eligibilityIncludes?: Array<number>;

    eligibilityExcludes?: Array<number>;

    requireResume: boolean;

    isPublic: boolean;

    submissionFreeze: string;

    submissionUnfreeze: string;

    isEligible: boolean;

}
export namespace Tournament {
}
