/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface UserProfilePrivate {
    gender: models.GenderEnum;

    genderDetails?: string;

    school?: string;

    biography?: string;

    kerberos?: string;

    avatarUrl: string;

    hasAvatar: boolean;

    hasResume: boolean;

    country: models.CountryEnum;

}
export namespace UserProfilePrivate {
}
