repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [css, html, javascript, json, jsx, markdown]
        exclude: ^frontend/public/assets

  - repo: local
    hooks:
      - id: black-conda
        name: black-conda
        entry: black
        language: conda
        require_serial: true
        types_or: [python, pyi]

      - id: flake8-conda
        name: flake8-conda
        entry: flake8
        language: conda
        require_serial: true
        types_or: [python, pyi]
        args: ["--max-line-length=88", "--max-complexity=18"]

      - id: isort-conda
        name: isort-conda
        entry: isort
        language: conda
        require_serial: true
        types_or: [python, pyi]
        args: ["--filter-files"]

      - id: mypy-conda
        name: mypy-conda
        entry: mypy
        language: conda
        require_serial: true
        types_or: [python, pyi]

      - id: pyupgrade-conda
        name: pyupgrade-conda
        entry: pyupgrade
        language: conda
        require_serial: true
        types_or: [python, pyi]
