repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt

  - repo: local
    hooks:
      - id: black-conda
        name: black-conda
        entry: black
        language: conda
        require_serial: true
        types_or: [python, pyi]
        exclude: ^backend/.*/migrations

      - id: flake8-conda
        name: flake8-conda
        entry: flake8
        language: conda
        require_serial: true
        types_or: [python, pyi]
        args: ["--max-line-length=88", "--max-complexity=18"]
        exclude: ^backend/.*/migrations

      - id: isort-conda
        name: isort-conda
        entry: isort
        language: conda
        require_serial: true
        types_or: [python, pyi]
        args: ["--filter-files"]
        exclude: ^backend/.*/migrations

      - id: mypy-conda
        name: mypy-conda
        entry: mypy
        language: conda
        require_serial: true
        types_or: [python, pyi]
        exclude: ^backend/.*/migrations

      - id: pyupgrade-conda
        name: pyupgrade-conda
        entry: pyupgrade
        language: conda
        require_serial: true
        types_or: [python, pyi]
        exclude: ^backend/.*/migrations
