[tool.isort]
profile = "black"
src_paths = ["backend"]
include_trailing_comma = true
ensure_newline_before_comments = true
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.10"
mypy_path = "backend"
ignore_missing_imports = true
scripts_are_modules = true
plugins = "mypy_django_plugin.main"

[tool.django-stubs]
django_settings_module = "siarnaq.settings"
