/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ScrimmageRequest {
    id: number;

    episode: string;

    created: string;

    status: models.ScrimmageRequestStatusEnum;

    is_ranked: boolean;

    requested_by: number;

    requested_by_name: string;

    requested_by_rating: number;

    requested_to: number;

    requested_to_name: string;

    requested_to_rating: number;

    player_order: models.PlayerOrderEnum;

    maps: Array<string>;

    map_names: Array<string>;

}
export namespace ScrimmageRequest {
}
