/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TeamProfilePrivate {
    quote?: string;

    biography?: string;

    has_avatar: boolean;

    has_report?: boolean;

    avatar_url: string;

    rating: number;

    auto_accept_ranked?: boolean;

    auto_accept_unranked?: boolean;

    eligible_for?: Array<number>;

}
