# Generated by Django 4.1.2 on 2022-11-26 20:29

from django.db import migrations, models
import django.db.models.deletion
import siarnaq.api.teams.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mean", models.FloatField(default=1500.0)),
                ("n", models.PositiveIntegerField(default=0)),
                ("value", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "join_key",
                    models.SlugField(
                        default=siarnaq.api.teams.models.make_team_join_key,
                        editable=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("R", "Regular"),
                            ("X", "Inactive"),
                            ("S", "Staff"),
                            ("O", "Invisible"),
                        ],
                        default="R",
                        max_length=1,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="episodes.episode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamProfile",
            fields=[
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="teams.team",
                    ),
                ),
                ("quote", models.CharField(blank=True, max_length=80)),
                ("biography", models.TextField(blank=True, max_length=1024)),
                ("has_avatar", models.BooleanField(default=False)),
                ("avatar_uuid", models.UUIDField(default=uuid.uuid4)),
                ("auto_accept_ranked", models.BooleanField(default=True)),
                ("auto_accept_unranked", models.BooleanField(default=True)),
            ],
        ),
    ]
