# Generated by Django 4.1.2 on 2022-11-26 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("episodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="teamprofile",
            name="eligible_for",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="episodes.eligibilitycriterion"
            ),
        ),
        migrations.AddField(
            model_name="teamprofile",
            name="rating",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="teams.rating"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("episode", "name"), name="team-unique-episode-name"
            ),
        ),
    ]
