# Generated by Django 4.1.2 on 2022-12-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamprofile",
            name="avatar_uuid",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
