# Generated by Django 4.1.2 on 2022-11-28 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[ -~]*$", message="Use ASCII characters only."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="teamprofile",
            name="quote",
            field=models.CharField(
                blank=True,
                max_length=80,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[ -~]*$", message="Use ASCII characters only."
                    )
                ],
            ),
        ),
    ]
