# Generated by Django 4.1.2 on 2022-12-30 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_name_alter_teamprofile_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamprofile",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to="teams.team",
            ),
        ),
    ]
