# Generated by Django 4.1.2 on 2022-12-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_name_alter_teamprofile_quote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamprofile",
            old_name="has_avatar",
            new_name="has_uploaded_avatar",
        ),
        migrations.AlterField(
            model_name="teamprofile",
            name="avatar_uuid",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
