# Generated by Django 4.1.2 on 2023-01-22 17:40

from django.db import migrations, models

def set_all_no_autoaccept(apps, schema_editor):
    TeamProfile = apps.get_model("teams", "TeamProfile")
    TeamProfile.objects.update(auto_accept_ranked=False)

class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_alter_teamprofile_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamprofile",
            name="auto_accept_ranked",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_all_no_autoaccept),
    ]
