# Generated by Django 4.1.2 on 2023-01-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0007_remove_episode_pass_requirement_out_of_and_more"),
        ("teams", "0005_alter_teamprofile_auto_accept_ranked"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_score", models.PositiveSmallIntegerField()),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_players",
                        to="episodes.episode",
                    ),
                ),
                ("maps", models.ManyToManyField(to="episodes.map")),
                (
                    "reference_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
        ),
    ]
