# Generated by Django 4.1.2 on 2023-01-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_classrequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamprofile",
            name="has_report",
            field=models.BooleanField(default=False),
        ),
    ]
