# Generated by Django 4.0.6 on 2022-07-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='eligibility_excludes',
            field=models.ManyToManyField(related_name='exclude_tournaments', to='teams.eligibilitycriterion'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='eligibility_includes',
            field=models.ManyToManyField(related_name='include_tournaments', to='teams.eligibilitycriterion'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='episodes.episode'),
        ),
        migrations.AddField(
            model_name='map',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='episodes.episode'),
        ),
        migrations.AddConstraint(
            model_name='tournamentround',
            constraint=models.UniqueConstraint(fields=('tournament', 'challonge_id'), name='round-unique-tournament-challonge'),
        ),
        migrations.AddConstraint(
            model_name='map',
            constraint=models.UniqueConstraint(fields=('episode', 'name'), name='map-unique-episode-name'),
        ),
    ]
