# Generated by Django 4.1.2 on 2023-01-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="release_version",
            new_name="release_version_public",
        ),
        migrations.AddField(
            model_name="episode",
            name="artifact_name",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="episode",
            name="release_version_saturn",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="episode",
            name="scaffold",
            field=models.URLField(blank=True),
        ),
    ]
