# Generated by Django 4.1.2 on 2023-01-17 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0003_remove_tournament_challonge_private_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="display_date",
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
    ]
