# Generated by Django 4.1.2 on 2023-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0004_tournament_display_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tournamentround",
            name="round-unique-tournament-challonge",
        ),
        migrations.RenameField(
            model_name="tournamentround",
            old_name="challonge_id",
            new_name="external_id",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="challonge_id_private",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="challonge_id_public",
        ),
        migrations.AddField(
            model_name="tournament",
            name="external_id_private",
            field=models.SlugField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="tournament",
            name="external_id_public",
            field=models.SlugField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name="tournamentround",
            constraint=models.UniqueConstraint(
                fields=("tournament", "external_id"),
                name="round-unique-tournament-bracket",
            ),
        ),
    ]
