# Generated by Django 4.1.2 on 2023-01-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "episodes",
            "0005_remove_tournamentround_round-unique-tournament-challonge_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentround",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
