# Generated by Django 4.1.2 on 2025-01-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0008_episode_release_version_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="language",
            field=models.CharField(
                choices=[
                    ("java8", "Java 8"),
                    ("java21", "Java 21"),
                    ("py3", "Python 3"),
                ],
                max_length=8,
            ),
        ),
    ]
