# Generated by Django 4.1.2 on 2025-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0010_episode_is_allowed_ranked_scrimmage"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="ranked_scrimmage_hourly_limit",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="episode",
            name="unranked_scrimmage_hourly_limit",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
