# Generated by Django 4.1.2 on 2025-11-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0011_episode_ranked_scrimmage_hourly_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilitycriterion",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
    ]
