# Generated by Django 4.1.2 on 2025-12-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0012_eligibilitycriterion_is_private"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("java8", "Java 8"),
                            ("java21", "Java 21"),
                            ("py3", "Python 3"),
                        ],
                        help_text="The language code (e.g., 'java8', 'py3')",
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.AlterField(
            model_name="episode",
            name="language",
            field=models.CharField(
                choices=[
                    ("java8", "Java 8"),
                    ("java21", "Java 21"),
                    ("py3", "Python 3"),
                ],
                help_text="Deprecated: use languages M2M field instead.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="The implementation languages supported for this episode.",
                related_name="episodes",
                to="episodes.programminglanguage",
            ),
        ),
    ]
