# Generated by Django 4.1.2 on 2025-12-31 06:49

from django.db import migrations


def migrate_language_data(apps, schema_editor):
    """Populate ProgrammingLanguage and migrate Episode.language → Episode.languages and Submission.language."""
    ProgrammingLanguage = apps.get_model("episodes", "ProgrammingLanguage")
    Episode = apps.get_model("episodes", "Episode")
    Submission = apps.get_model("compete", "Submission")

    # 1. Create ProgrammingLanguage records
    languages = [
        {"code": "java8", "display_name": "Java 8"},
        {"code": "java21", "display_name": "Java 21"},
        {"code": "py3", "display_name": "Python 3"},
    ]
    for lang in languages:
        ProgrammingLanguage.objects.get_or_create(
            code=lang["code"],
            defaults={"display_name": lang["display_name"]}
        )

    # 2. Migrate Episode.language (CharField) → Episode.languages (M2M)
    for episode in Episode.objects.all():
        if episode.language:  # Read from old CharField
            try:
                lang_obj = ProgrammingLanguage.objects.get(code=episode.language)
                episode.languages.add(lang_obj)  # Add to new M2M
            except ProgrammingLanguage.DoesNotExist:
                print(f"Warning: Language '{episode.language}' not found for episode '{episode.name_short}'")

    # 3. Migrate Episode.language → Submission.language (FK)
    for episode in Episode.objects.all():
        if episode.language:
            try:
                lang_obj = ProgrammingLanguage.objects.get(code=episode.language)
                # Assign language to all submissions for this episode
                Submission.objects.filter(
                    episode=episode,
                    language__isnull=True
                ).update(language=lang_obj)
            except ProgrammingLanguage.DoesNotExist:
                print(f"Warning: Language '{episode.language}' not found for episode '{episode.name_short}'")


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0013_programminglanguage_alter_episode_language_and_more"),
        ("compete", "0010_submission_language"),
    ]

    operations = [
        migrations.RunPython(migrate_language_data, migrations.RunPython.noop),
    ]
