# Generated by Django 4.1.2 on 2025-12-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0014_migrate_language_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="language",
        ),
    ]
