/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HistoricalRating } from './HistoricalRating';
import {
    HistoricalRatingFromJSON,
    HistoricalRatingFromJSONTyped,
    HistoricalRatingToJSON,
} from './HistoricalRating';

/**
 * 
 * @export
 * @interface PaginatedHistoricalRatingList
 */
export interface PaginatedHistoricalRatingList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedHistoricalRatingList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHistoricalRatingList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHistoricalRatingList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<HistoricalRating>}
     * @memberof PaginatedHistoricalRatingList
     */
    results?: Array<HistoricalRating>;
}

/**
 * Check if a given object implements the PaginatedHistoricalRatingList interface.
 */
export function instanceOfPaginatedHistoricalRatingList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedHistoricalRatingListFromJSON(json: any): PaginatedHistoricalRatingList {
    return PaginatedHistoricalRatingListFromJSONTyped(json, false);
}

export function PaginatedHistoricalRatingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedHistoricalRatingList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(HistoricalRatingFromJSON)),
    };
}

export function PaginatedHistoricalRatingListToJSON(value?: PaginatedHistoricalRatingList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(HistoricalRatingToJSON)),
    };
}

