/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserResumeRequest
 */
export interface UserResumeRequest {
    /**
     *
     * @type {Blob}
     * @memberof UserResumeRequest
     */
    resume: Blob;
}

/**
 * Check if a given object implements the UserResumeRequest interface.
 */
export function instanceOfUserResumeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resume" in value;

    return isInstance;
}

export function UserResumeRequestFromJSON(json: any): UserResumeRequest {
    return UserResumeRequestFromJSONTyped(json, false);
}

export function UserResumeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResumeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'resume': json['resume'],
    };
}

export function UserResumeRequestToJSON(value?: UserResumeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'resume': value.resume,
    };
}
