/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum LanguagesEnum {
    Java8 = 'java8',
    Java21 = 'java21',
    Py3 = 'py3'
}


export function LanguagesEnumFromJSON(json: any): LanguagesEnum {
    return LanguagesEnumFromJSONTyped(json, false);
}

export function LanguagesEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguagesEnum {
    return json as LanguagesEnum;
}

export function LanguagesEnumToJSON(value?: LanguagesEnum | null): any {
    return value as any;
}

