# Generated by Django 4.1.2 on 2022-11-26 20:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Created"),
                            ("QUE", "Queued"),
                            ("RUN", "Running"),
                            ("TRY", "Retry"),
                            ("OK!", "Completed"),
                            ("ERR", "Errored"),
                            ("CAN", "Cancelled"),
                        ],
                        default="NEW",
                        max_length=3,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("logs", models.TextField(blank=True)),
                ("num_failures", models.PositiveSmallIntegerField(default=0)),
                ("alternate_order", models.BooleanField()),
                ("is_ranked", models.BooleanField()),
                ("replay", models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MatchParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_index", models.PositiveSmallIntegerField()),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrimmageRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("Y", "Accepted"),
                            ("N", "Rejected"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("is_ranked", models.BooleanField()),
                (
                    "player_order",
                    models.CharField(
                        choices=[
                            ("+", "Requester First"),
                            ("-", "Requester Last"),
                            ("?", "Shuffled"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Created"),
                            ("QUE", "Queued"),
                            ("RUN", "Running"),
                            ("TRY", "Retry"),
                            ("OK!", "Completed"),
                            ("ERR", "Errored"),
                            ("CAN", "Cancelled"),
                        ],
                        default="NEW",
                        max_length=3,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("logs", models.TextField(blank=True)),
                ("num_failures", models.PositiveSmallIntegerField(default=0)),
                ("accepted", models.BooleanField(default=False)),
                ("package", models.CharField(blank=True, max_length=32)),
                ("description", models.CharField(blank=True, max_length=128)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="episodes.episode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
