# Generated by Django 4.0.6 on 2022-07-30 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Created'), ('QUE', 'Queued'), ('RUN', 'Running'), ('TRY', 'Retry'), ('OK!', 'Completed'), ('ERR', 'Errored'), ('CAN', 'Cancelled')], default='NEW', max_length=3)),
                ('logs', models.TextField(blank=True)),
                ('alternate_color', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_ranked', models.BooleanField()),
                ('replay', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrimmageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('Y', 'Accepted'), ('N', 'Rejected'), ('X', 'Cancelled')], max_length=1)),
                ('is_ranked', models.BooleanField()),
                ('color', models.CharField(choices=[('RRR', 'Always Red'), ('BBB', 'Always Blue'), ('RBR', 'Alternate Red'), ('BRB', 'Alternate Blue'), ('???', 'Alternate Random')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Created'), ('QUE', 'Queued'), ('RUN', 'Running'), ('TRY', 'Retry'), ('OK!', 'Completed'), ('ERR', 'Errored'), ('CAN', 'Cancelled')], default='NEW', max_length=3)),
                ('logs', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('package', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
