# Generated by Django 4.0.6 on 2022-07-30 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compete', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('episodes', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='episodes.episode'),
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='teams.team'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrimmagerequest',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrimmage_requests', to='episodes.episode'),
        ),
        migrations.AddField(
            model_name='scrimmagerequest',
            name='maps',
            field=models.ManyToManyField(related_name='scrimmage_requests', to='episodes.map'),
        ),
        migrations.AddField(
            model_name='scrimmagerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrimmage_requests_sent', to='teams.team'),
        ),
        migrations.AddField(
            model_name='scrimmagerequest',
            name='requested_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrimmage_requests_received', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='rating_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preceding_participation', to='teams.rating'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='rating_old',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='succeeding_participation', to='teams.rating'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='compete.submission'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blue_match', to='compete.matchparticipant'),
        ),
        migrations.AddField(
            model_name='match',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='episodes.episode'),
        ),
        migrations.AddField(
            model_name='match',
            name='maps',
            field=models.ManyToManyField(related_name='matches', to='episodes.map'),
        ),
        migrations.AddField(
            model_name='match',
            name='red',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='red_match', to='compete.matchparticipant'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='episodes.tournamentround'),
        ),
    ]
