# Generated by Django 4.1.2 on 2022-11-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("compete", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="teams.team",
            ),
        ),
    ]
