# Generated by Django 4.1.2 on 2022-11-26 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compete", "0002_initial"),
        ("teams", "0001_initial"),
        ("episodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scrimmagerequest",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scrimmage_requests",
                to="episodes.episode",
            ),
        ),
        migrations.AddField(
            model_name="scrimmagerequest",
            name="maps",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, related_name="scrimmage_requests", to="episodes.map"
            ),
        ),
        migrations.AddField(
            model_name="scrimmagerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scrimmage_requests_sent",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="scrimmagerequest",
            name="requested_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scrimmage_requests_received",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="compete.match",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="previous_participation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_participation",
                to="compete.matchparticipant",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="teams.rating",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participations",
                to="compete.submission",
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participations",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="episodes.episode",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="maps",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, related_name="matches", to="episodes.map"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="episodes.tournamentround",
            ),
        ),
    ]
