# Generated by Django 4.1.2 on 2023-01-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compete", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="challonge_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="challonge_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
