# Generated by Django 4.1.2 on 2023-01-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compete", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="package",
            field=models.CharField(max_length=32),
        ),
    ]
