# Generated by Django 4.1.2 on 2023-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compete", "0004_match_challonge_id_matchparticipant_challonge_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="challonge_id",
            new_name="external_id_private",
        ),
        migrations.RemoveField(
            model_name="matchparticipant",
            name="challonge_id",
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
