# Generated by Django 4.1.2 on 2023-01-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "episodes",
            "0005_remove_tournamentround_round-unique-tournament-challonge_and_more",
        ),
        (
            "compete",
            "0006_rename_external_id_matchparticipant_external_id_private_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="tournament_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="episodes.tournamentround",
            ),
        ),
    ]
