# Generated by Django 4.1.2 on 2023-01-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compete", "0007_alter_match_tournament_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchparticipant",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="compete.match",
            ),
        ),
        migrations.AlterField(
            model_name="matchparticipant",
            name="previous_participation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="next_participation",
                to="compete.matchparticipant",
            ),
        ),
    ]
