# Generated by Django 4.1.2 on 2025-01-13 19:22

from django.db import migrations, models


def create_default_admin_settings(apps, schema_editor):
    # Get the AdminSettings model
    AdminSettings = apps.get_model("compete", "AdminSettings")
    if not AdminSettings.objects.exists():
        # Create a default instance
        AdminSettings.objects.create(is_allowed_ranked_scrimmages=True)


class Migration(migrations.Migration):

    dependencies = [
        ("compete", "0008_alter_matchparticipant_match_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_allowed_ranked_scrimmages", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Admin Setting",
                "verbose_name_plural": "Admin Settings",
            },
        ),
        migrations.RunPython(create_default_admin_settings),
    ]
