# Generated by Django 4.1.2 on 2025-12-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0013_programminglanguage_alter_episode_language_and_more"),
        ("compete", "0009_adminsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="The programming language of this submission.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="episodes.programminglanguage",
            ),
        ),
    ]
