/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamProfilePrivateRequest
 */
export interface TeamProfilePrivateRequest {
    /**
     * 
     * @type {string}
     * @memberof TeamProfilePrivateRequest
     */
    quote?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamProfilePrivateRequest
     */
    biography?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TeamProfilePrivateRequest
     */
    has_report?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TeamProfilePrivateRequest
     */
    auto_accept_ranked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TeamProfilePrivateRequest
     */
    auto_accept_unranked?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof TeamProfilePrivateRequest
     */
    eligible_for?: Array<number>;
}

/**
 * Check if a given object implements the TeamProfilePrivateRequest interface.
 */
export function instanceOfTeamProfilePrivateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamProfilePrivateRequestFromJSON(json: any): TeamProfilePrivateRequest {
    return TeamProfilePrivateRequestFromJSONTyped(json, false);
}

export function TeamProfilePrivateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamProfilePrivateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quote': !exists(json, 'quote') ? undefined : json['quote'],
        'biography': !exists(json, 'biography') ? undefined : json['biography'],
        'has_report': !exists(json, 'has_report') ? undefined : json['has_report'],
        'auto_accept_ranked': !exists(json, 'auto_accept_ranked') ? undefined : json['auto_accept_ranked'],
        'auto_accept_unranked': !exists(json, 'auto_accept_unranked') ? undefined : json['auto_accept_unranked'],
        'eligible_for': !exists(json, 'eligible_for') ? undefined : json['eligible_for'],
    };
}

export function TeamProfilePrivateRequestToJSON(value?: TeamProfilePrivateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quote': value.quote,
        'biography': value.biography,
        'has_report': value.has_report,
        'auto_accept_ranked': value.auto_accept_ranked,
        'auto_accept_unranked': value.auto_accept_unranked,
        'eligible_for': value.eligible_for,
    };
}

