/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamAvatarRequest
 */
export interface TeamAvatarRequest {
    /**
     * 
     * @type {Blob}
     * @memberof TeamAvatarRequest
     */
    avatar: Blob;
}

/**
 * Check if a given object implements the TeamAvatarRequest interface.
 */
export function instanceOfTeamAvatarRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "avatar" in value;

    return isInstance;
}

export function TeamAvatarRequestFromJSON(json: any): TeamAvatarRequest {
    return TeamAvatarRequestFromJSONTyped(json, false);
}

export function TeamAvatarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamAvatarRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatar': json['avatar'],
    };
}

export function TeamAvatarRequestToJSON(value?: TeamAvatarRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatar': value.avatar,
    };
}

