/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfilePublicRequest
 */
export interface UserProfilePublicRequest {
    /**
     * 
     * @type {string}
     * @memberof UserProfilePublicRequest
     */
    school?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfilePublicRequest
     */
    biography?: string;
}

/**
 * Check if a given object implements the UserProfilePublicRequest interface.
 */
export function instanceOfUserProfilePublicRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserProfilePublicRequestFromJSON(json: any): UserProfilePublicRequest {
    return UserProfilePublicRequestFromJSONTyped(json, false);
}

export function UserProfilePublicRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfilePublicRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'school': !exists(json, 'school') ? undefined : json['school'],
        'biography': !exists(json, 'biography') ? undefined : json['biography'],
    };
}

export function UserProfilePublicRequestToJSON(value?: UserProfilePublicRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'school': value.school,
        'biography': value.biography,
    };
}

